### ISSUE TITLE
Is svelte-email still maintained?

### ISSUE THREAD

**Issue by socketopp** [steveninety/svelte-email-tailwind#7]
From what I've read, https://github.com/cmjoseph07/svelty-email is the current lib that continues where svelte-email left off.
https://github.com/carstenlebek/svelte-email/issues/25

**Comment by steveninety** [comment]
Doesn't seem like the original svelte-email is being maintained (otherwise I would've contributed there instead of maintaining this separate package). My contribution is the tailwind integration. I'd love to make it a standalone Vite plugin that integrates into an existing project (so that devs can use a designated svelte email package of choice, whether that is the original, or the one apparently maintained by @cmjoseph07). But unfortunately it needs access to the components to properly merge styles and inline them.
